query GetAllTeachersFullInfo($cmkName: String = "") {
  workers(
    filters: {
      category: { in: ["teacher"] }
      cycle_commission: { name: { contains: $cmkName } }
    }
    sort: "name:asc"
    pagination: { pageSize: 200 }
  ) {
    data {
      id
      attributes {
        name
        photo {
          data {
            attributes {
              url
            }
          }
        }
        email
        phone
        lessons {
          data {
            attributes {
              name
            }
          }
        }
        slug
        cycle_commission {
          data {
            attributes {
              name
              slug
            }
          }
        }
      }
    }
  }
}
