query GetNews($currentPage: Int = 1, $pageSize: Int = 3) {
  novinas(sort: "date:desc", pagination: { page: $currentPage, pageSize: $pageSize }) {
    meta {
      pagination {
        total
        page
        pageSize
        pageCount
      }
    }
    data {
      id
      attributes {
        title
        body
        date
        main_photo {
          data {
            attributes {
              url
              width
              height
            }
          }
        }
        collage_photos {
          data {
            id
            attributes {
              url
              width
              height
            }
          }
        }
        video_url
        news_tags {
          data {
            id
            attributes {
              title
            }
          }
        }
      }
    }
  }
}

query GetAllNovinasId {
  novinas(pagination: { pageSize: 50000 }) {
    data {
      id
      attributes {
        date
      }
    }
  }
}
