query GetSubdiv($subdivSlug: String) {
  subdivisions(filters: { slug: { in: [$subdivSlug] } }, pagination: { pageSize: 100 }) {
    data {
      id
      attributes {
        name
        slug
        main_photo {
          data {
            attributes {
              url
              width
              height
            }
          }
        }
        SEO {
          title
          description
          meta {
            id
            name
            content
          }
        }
        page_url
        layout
        page_components {
          ...GetAccordionComponent
          ...GetBodyComponent
          ...GetButtonImagesComponent
          ...GetButtonLinkComponent
          ...GetEducationBooksComponent
          ...GetBlocksPanoramsComponent
          ...GetPartnersBlockComponent
          ...GetPhotosGalleryComponent
          ...GetTwoColumnWithImageComponent
          ...GetBlocksPersonComponent
        }
        right_sidebar {
          ...GetAccordionComponent
          ...GetBodyComponent
          ...GetButtonImagesComponent
          ...GetButtonLinkComponent
          ...GetEducationBooksComponent
          ...GetBlocksPanoramsComponent
          ...GetPartnersBlockComponent
          ...GetPhotosGalleryComponent
          ...GetTwoColumnWithImageComponent
          ...GetBlocksPersonComponent
        }
        left_sidebar {
          ...GetAccordionComponent
          ...GetBodyComponent
          ...GetButtonImagesComponent
          ...GetButtonLinkComponent
          ...GetEducationBooksComponent
          ...GetBlocksPanoramsComponent
          ...GetPartnersBlockComponent
          ...GetPhotosGalleryComponent
          ...GetTwoColumnWithImageComponent
          ...GetBlocksPersonComponent
        }
      }
    }
  }
}
